#!/usr/bin/expect
# 先安装expect：sudo apt-get install expect 或 yum -y install expect
# 至少要等待1秒
set timeout 1

#设置密码
set passwd "1234"

# spawn将开启一个新的进程，可切换目录，执行一个命令
spawn 进程

# 判断上述进程的输出结果中是否有“password”的字符串(不区分大小写)
# 若有则立即返回，否则就等待一段时间后返回，等待时长就是开头设置的1秒
expect "password"

# 向上面的进程发送字符串中的密码, 并且自动敲Enter健(\r)
send "$passwd\r"

#expect命令结束
expect eof

#执行完成后保持交互状态
interact
